apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
spec:
  project: default
  source:
    repoURL: https://github.com/meetreks/gitops.git
    path: ./
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
