apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
spec:
  project: default
  source:
    repoURL: https://github.com/meetreks/gitops.git
    targetRevision: main
    path: /
    helm:
      values: |
        message: "hello world"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
